name: Build NeoForge 1.21.1

on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  build-target:
    name: Build NeoForge 1.21.1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Build NeoForge 1.21.1
        working-directory: neoforge-1.21.1
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proxy-protocol-1.21.1-neoforge
          path: neoforge-1.21.1/build/libs/**/*.jar
